/**
 * LaTeX Resume Generator for CV-Genie
 * 
 * This utility generates a professional, compilable LaTeX document from resume data.
 * The generated .tex file can be compiled with pdflatex or xelatex.
 * 
 * Compilation Instructions:
 * 1. Save this file as resume.tex
 * 2. Compile with: pdflatex resume.tex
 * 3. Or use: xelatex resume.tex (for better font support)
 * 4. Run twice if you see reference warnings
 * 
 * Required LaTeX Distribution:
 * - TeX Live (recommended): https://www.tug.org/texlive/
 * - MiKTeX (Windows): https://miktex.org/
 * - MacTeX (macOS): https://www.tug.org/mactex/
 */

interface PersonalInfo {
  name: string;
  location: string;
  email: string;
  github: string;
  linkedin: string;
  twitter: string;
}

interface Skill {
  category: string;
  items: string;
}

interface Education {
  institute: string;
  degree: string;
  duration: string;
  score: string;
}

interface Experience {
  role: string;
  organization: string;
  location: string;
  duration: string;
  points: string[];
}

interface Project {
  title: string;
  description: string;
  points: string[];
  github: string;
}

interface Achievement {
  items: string;
}

interface ResumeData {
  info: PersonalInfo;
  skills: Skill[];
  education: Education[];
  experience: Experience[];
  projects: Project[];
  achievement: Achievement[];
}

/**
 * Escapes special LaTeX characters to prevent compilation errors
 * Handles: & % $ # _ { } ~ ^ \
 */
function escapeLatex(text: string): string {
  if (!text) return '';
  
  return text
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/&/g, '\\&')
    .replace(/%/g, '\\%')
    .replace(/\$/g, '\\$')
    .replace(/#/g, '\\#')
    .replace(/_/g, '\\_')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}')
    // Handle URLs - don't escape if it's already in a URL
    .replace(/\\textbackslash\{\}/g, '\\textbackslash{}');
}

/**
 * Formats a URL for LaTeX hyperref package
 * Preserves the URL structure while making it clickable
 */
function formatUrl(url: string): string {
  if (!url) return '';
  
  // Remove http:// or https:// for display, but keep for href
  const displayUrl = url.replace(/^https?:\/\//, '');
  
  // Don't escape URLs - hyperref handles them
  return `\\href{${url}}{${displayUrl}}`;
}

/**
 * Formats an email for LaTeX with mailto link
 */
function formatEmail(email: string): string {
  if (!email) return '';
  return `\\href{mailto:${email}}{${email}}`;
}

/**
 * Generates the LaTeX document header with packages and styling
 */
function generateHeader(): string {
  return `%============================================================
% LaTeX Resume - Generated by CV-Genie
%============================================================
% This is a professional, compilable LaTeX resume document.
% 
% COMPILATION INSTRUCTIONS:
% 1. Install a LaTeX distribution (TeX Live, MiKTeX, or MacTeX)
% 2. Save this file as resume.tex
% 3. Run: pdflatex resume.tex
% 4. Or use: xelatex resume.tex (recommended for better fonts)
%
% CUSTOMIZATION TIPS:
% - Adjust margins in \\geometry{} below
% - Change section spacing by modifying \\titlespacing
% - Add more sections as needed
% - Modify fonts by uncommenting font packages
%============================================================

\\documentclass[11pt,a4paper]{article}

% ========== PACKAGES ==========
\\usepackage[utf8]{inputenc}           % UTF-8 encoding support
\\usepackage[T1]{fontenc}              % Font encoding
\\usepackage{geometry}                 % Page margins
\\usepackage{enumitem}                 % List customization
\\usepackage{hyperref}                 % Hyperlinks (email, URLs)
\\usepackage{titlesec}                 % Section title formatting
\\usepackage{xcolor}                   % Colors

% ========== PAGE SETUP ==========
\\geometry{
  top=1cm,
  bottom=1cm,
  left=1.5cm,
  right=1.5cm
}

% Remove page numbers
\\pagestyle{empty}

% ========== HYPERLINK SETUP ==========
\\hypersetup{
  colorlinks=true,
  linkcolor=blue,
  urlcolor=blue,
  pdfborder={0 0 0}
}

% ========== SECTION FORMATTING ==========
\\titleformat{\\section}
  {\\Large\\bfseries\\scshape\\raggedright}
  {}{0em}{}[\\titlerule]
\\titlespacing{\\section}{0pt}{10pt}{5pt}

% ========== LIST FORMATTING ==========
\\setlist[itemize]{leftmargin=*, nosep, label=\\textbullet}

% ========== CUSTOM COMMANDS ==========
% Command for experience/project headers
\\newcommand{\\experienceheader}[4]{
  \\textbf{#1} \\hfill \\textit{#2} \\\\
  \\textit{#3} \\hfill #4
}

% Command for education entries
\\newcommand{\\educationentry}[4]{
  \\textbf{#1} \\hfill \\textit{#2} \\\\
  #3 \\hfill #4
}

%============================================================
\\begin{document}

`;
}

/**
 * Generates the personal information section (header)
 */
function generatePersonalInfo(info: PersonalInfo): string {
  if (!info.name && !info.email && !info.location) return '';
  
  let latex = '% ========== PERSONAL INFORMATION ==========\n';
  latex += '\\begin{center}\n';
  
  // Name
  if (info.name) {
    latex += `  {\\Huge\\textbf{${escapeLatex(info.name)}}}\\\\[3pt]\n`;
  }
  
  // Contact details on one line
  const contactDetails: string[] = [];
  
  if (info.location) {
    contactDetails.push(escapeLatex(info.location));
  }
  
  if (info.email) {
    contactDetails.push(formatEmail(info.email));
  }
  
  if (info.github) {
    const githubUrl = info.github.startsWith('http') ? info.github : `https://github.com/${info.github}`;
    contactDetails.push(`GitHub: ${formatUrl(githubUrl)}`);
  }
  
  if (info.linkedin) {
    const linkedinUrl = info.linkedin.startsWith('http') ? info.linkedin : `https://linkedin.com/in/${info.linkedin}`;
    contactDetails.push(`LinkedIn: ${formatUrl(linkedinUrl)}`);
  }
  
  if (info.twitter) {
    const twitterUrl = info.twitter.startsWith('http') ? info.twitter : `https://twitter.com/${info.twitter}`;
    contactDetails.push(`Twitter: ${formatUrl(twitterUrl)}`);
  }
  
  if (contactDetails.length > 0) {
    latex += `  ${contactDetails.join(' $|$ ')}\\\\[3pt]\n`;
  }
  
  latex += '\\end{center}\n\n';
  
  return latex;
}

/**
 * Generates the skills section
 */
function generateSkills(skills: Skill[]): string {
  if (!skills || skills.length === 0 || !skills.some(s => s.category || s.items)) {
    return '';
  }
  
  let latex = '% ========== SKILLS ==========\n';
  latex += '\\section{Skills}\n';
  
  for (const skill of skills) {
    if (skill.category || skill.items) {
      const category = skill.category ? `\\textbf{${escapeLatex(skill.category)}:}` : '';
      const items = skill.items ? escapeLatex(skill.items) : '';
      
      if (category && items) {
        latex += `${category} ${items}\\\\[3pt]\n`;
      } else if (items) {
        latex += `${items}\\\\[3pt]\n`;
      }
    }
  }
  
  latex += '\n';
  return latex;
}

/**
 * Generates the education section
 */
function generateEducation(education: Education[]): string {
  if (!education || education.length === 0 || !education.some(e => e.institute || e.degree)) {
    return '';
  }
  
  let latex = '% ========== EDUCATION ==========\n';
  latex += '\\section{Education}\n\n';
  
  for (const edu of education) {
    if (edu.institute || edu.degree) {
      const institute = escapeLatex(edu.institute || '');
      const degree = escapeLatex(edu.degree || '');
      const duration = escapeLatex(edu.duration || '');
      const score = escapeLatex(edu.score || '');
      
      latex += `\\educationentry{${institute}}{${duration}}{${degree}}{${score}}\\\\[8pt]\n\n`;
    }
  }
  
  return latex;
}

/**
 * Generates the experience section
 */
function generateExperience(experience: Experience[]): string {
  if (!experience || experience.length === 0 || !experience.some(e => e.role || e.organization)) {
    return '';
  }
  
  let latex = '% ========== EXPERIENCE ==========\n';
  latex += '\\section{Experience}\n\n';
  
  for (const exp of experience) {
    if (exp.role || exp.organization) {
      const role = escapeLatex(exp.role || '');
      const organization = escapeLatex(exp.organization || '');
      const location = escapeLatex(exp.location || '');
      const duration = escapeLatex(exp.duration || '');
      
      latex += `\\experienceheader{${role}}{${duration}}{${organization}}{${location}}\\\\[3pt]\n`;
      
      // Add bullet points
      if (exp.points && exp.points.length > 0 && exp.points.some(p => p)) {
        latex += '\\begin{itemize}\n';
        for (const point of exp.points) {
          if (point && point.trim()) {
            latex += `  \\item ${escapeLatex(point)}\n`;
          }
        }
        latex += '\\end{itemize}\n';
      }
      
      latex += '\\vspace{5pt}\n\n';
    }
  }
  
  return latex;
}

/**
 * Generates the projects section
 */
function generateProjects(projects: Project[]): string {
  if (!projects || projects.length === 0 || !projects.some(p => p.title)) {
    return '';
  }
  
  let latex = '% ========== PROJECTS ==========\n';
  latex += '\\section{Projects}\n\n';
  
  for (const project of projects) {
    if (project.title) {
      const title = escapeLatex(project.title || '');
      const description = escapeLatex(project.description || '');
      
      // Project title with GitHub link if available
      if (project.github) {
        latex += `\\textbf{${title}} $|$ ${formatUrl(project.github)}\\\\[3pt]\n`;
      } else {
        latex += `\\textbf{${title}}\\\\[3pt]\n`;
      }
      
      // Description
      if (description) {
        latex += `${description}\\\\[3pt]\n`;
      }
      
      // Project points
      if (project.points && project.points.length > 0 && project.points.some(p => p)) {
        latex += '\\begin{itemize}\n';
        for (const point of project.points) {
          if (point && point.trim()) {
            latex += `  \\item ${escapeLatex(point)}\n`;
          }
        }
        latex += '\\end{itemize}\n';
      }
      
      latex += '\\vspace{5pt}\n\n';
    }
  }
  
  return latex;
}

/**
 * Generates the achievements section
 */
function generateAchievements(achievements: Achievement[]): string {
  if (!achievements || achievements.length === 0 || !achievements.some(a => a.items)) {
    return '';
  }
  
  let latex = '% ========== ACHIEVEMENTS ==========\n';
  latex += '\\section{Achievements}\n\n';
  latex += '\\begin{itemize}\n';
  
  for (const achievement of achievements) {
    if (achievement.items && achievement.items.trim()) {
      latex += `  \\item ${escapeLatex(achievement.items)}\n`;
    }
  }
  
  latex += '\\end{itemize}\n\n';
  
  return latex;
}

/**
 * Generates the document footer
 */
function generateFooter(): string {
  return `%============================================================
% End of Resume
%============================================================
% To compile this document:
% 1. Run: pdflatex resume.tex
% 2. If you see warnings, run it again: pdflatex resume.tex
%
% For best results, use XeLaTeX: xelatex resume.tex
%
% Generated by CV-Genie - https://cv-genie.vercel.app
%============================================================
\\end{document}
`;
}

/**
 * Main function to generate complete LaTeX document
 * @param data Resume data including all sections
 * @returns Complete LaTeX document as string
 */
export function generateLatexResume(data: ResumeData): string {
  let latex = '';
  
  // Add header and preamble
  latex += generateHeader();
  
  // Add personal information
  latex += generatePersonalInfo(data.info);
  
  // Add all sections
  latex += generateSkills(data.skills);
  latex += generateEducation(data.education);
  latex += generateExperience(data.experience);
  latex += generateProjects(data.projects);
  latex += generateAchievements(data.achievement);
  
  // Add footer
  latex += generateFooter();
  
  return latex;
}

/**
 * Downloads the LaTeX file to the user's computer
 * @param data Resume data
 * @param filename Optional filename (default: "resume.tex")
 */
export function downloadLatexResume(data: ResumeData, filename: string = 'resume.tex'): void {
  const latexContent = generateLatexResume(data);
  
  // Create blob with LaTeX content
  const blob = new Blob([latexContent], { type: 'text/plain;charset=utf-8' });
  
  // Create download link
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  
  // Trigger download
  document.body.appendChild(link);
  link.click();
  
  // Cleanup
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
